import { Translation } from './types.ts';

export const TRANSLATIONS: Record<'en' | 'he', Translation> = {
  en: {
    title: 'The Smart Pantry',
    recipes: 'Recipes',
    orders: 'Orders',
    inventory: 'Inventory',
    shopping: 'Shopping',
    addRecipe: 'Add Recipe',
    recipeName: 'Recipe Name',
    ingredientName: 'Ingredient Name',
    quantity: 'Qty',
    unit: 'Unit',
    save: 'Save Changes',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    calculate: 'Calculate List',
    totalItems: 'Total Items',
    exportCsv: 'Export to Sheets',
    copyWhatsapp: 'Copy to WhatsApp',
    emptyRecipes: 'No recipes yet. Tap + to add one!',
    emptyOrders: 'Set quantities for your daily orders.',
    emptyInventory: 'Your pantry is empty. Add items you have in stock.',
    addIngredient: 'Add Item',
    recipeImage: 'Recipe Image',
    tapToUpload: 'Tap to upload photo',
    sortIngredients: 'Sort A-Z',
    searchPlaceholder: 'Search recipes...',
    allCategories: 'All',
    category: 'Category',
    aiScan: 'Scan Recipe (AI)',
    aiScanning: 'Analyzing recipe image...',
    aiScanError: 'Could not read recipe. Please try a clearer photo.',
    prepTime: 'Prep Time',
    cookTime: 'Cook Time',
    minutes: 'min',
    need: 'Need',
    inPantry: 'in pantry',
    fullyStocked: 'Fully Stocked / From Pantry',
    planningMode: 'Planning',
    cookingMode: 'Cooking',
    markAsCooked: 'Done!',
    ingredientsDeducted: 'Ingredients removed from pantry',
    completedToday: 'Finished Today',
    categories: {
      meat: 'Meat',
      dairy: 'Dairy',
      pareve: 'Pareve',
      dessert: 'Dessert',
      other: 'Other'
    },
    units: {
      kg: 'kg',
      grams: 'g',
      units: 'units',
      liters: 'L',
      cans: 'cans',
      packs: 'packs'
    }
  },
  he: {
    title: 'המזווה החכם',
    recipes: 'מתכונים',
    orders: 'הזמנות',
    inventory: 'מלאי',
    shopping: 'קניות',
    addRecipe: 'הוסף מתכון',
    recipeName: 'שם המתכון',
    ingredientName: 'שם המרכיב',
    quantity: 'כמות',
    unit: 'יחידה',
    save: 'שמור שינויים',
    cancel: 'ביטול',
    delete: 'מחק',
    edit: 'עריכה',
    calculate: 'חשב רשימה',
    totalItems: 'סה"כ פריטים',
    exportCsv: 'ייצא לגוגל שיטס',
    copyWhatsapp: 'העתק לוואטסאפ',
    emptyRecipes: 'אין מתכונים עדיין. לחץ על + להוספה!',
    emptyOrders: 'קבע כמויות להזמנות היומיות שלך.',
    emptyInventory: 'המלאי שלך ריק. הוסף מוצרים שיש לך בבית.',
    addIngredient: 'הוסף פריט',
    recipeImage: 'תמונת המנה',
    tapToUpload: 'לחץ להעלאת תמונה',
    sortIngredients: 'מיין א-ב',
    searchPlaceholder: 'חיפוש מתכונים...',
    allCategories: 'הכל',
    category: 'קטגוריה',
    aiScan: 'סרוק מתכון (AI)',
    aiScanning: 'מנתח את התמונה...',
    aiScanError: 'לא הצלחתי לקרוא את המתכון. נסה תמונה ברורה יותר.',
    prepTime: 'זמן הכנה',
    cookTime: 'זמן בישול',
    minutes: 'דקות',
    need: 'צריך',
    inPantry: 'במלאי',
    fullyStocked: 'קיים במלאי / לא דרוש קנייה',
    planningMode: 'תכנון',
    cookingMode: 'בישול',
    markAsCooked: 'בוצע!',
    ingredientsDeducted: 'המרכיבים הופחתו מהמלאי',
    completedToday: 'הוכנו היום',
    categories: {
      meat: 'בשרי',
      dairy: 'חלבי',
      pareve: 'פרווה',
      dessert: 'קינוח',
      other: 'אחר'
    },
    units: {
      kg: 'ק"ג',
      grams: 'גרם',
      units: 'יחידות',
      liters: 'ליטר',
      cans: 'קופסאות',
      packs: 'חבילות'
    }
  }
};

export const UNIT_OPTIONS: string[] = ['kg', 'grams', 'units', 'liters', 'cans', 'packs'];
export const CATEGORY_OPTIONS = ['meat', 'dairy', 'pareve', 'dessert', 'other'] as const;